### ISSUE TITLE
Please use .zip, tar or tar.gz for compressed files

### ISSUE THREAD

**Issue by unite-analytics** [ICT4SD/CyberSecurity_Strategies#2]
Would you please use .zip tar or tar.gz format for your compressed files instead of .rar? (for example for the file "new_tagged_json.rar" in the Fordham-PICASSO branch)
Thanks!

@ICT4SD/cybersecurity-strategies-members

**Comment by ericcaichuanze** [comment]
HI,
  Sorry for the confusion and I have re-uploaded the files in .zip
extension.
Best
Chuanze

2017-04-27 9:07 GMT-04:00 Unite Analytics <notifications@github.com>:

**Comment by unite-analytics** [comment]
Thanks!
